@startuml
!include ././Ticket.puml
!include ././Program.puml
!include ././SystemConfig.puml
!include ./Services/TicketService.puml
!include ./Controllers/IndexController.puml
!include ./Controllers/LoginController.puml
!include ./Controllers/TicketController.puml
!include ./Pages/Ticket.cshtml.puml
!include ./Migrations/20240220032644_AeroAssist.puml
!include ./Migrations/AeroAssistContextModelSnapshot.puml
!include ./Migrations/20240220032644_AeroAssist.Designer.puml
!include ./Models/TicketModel.puml
!include ./DB/DbContext.puml
!include ./Pages/Shared/_Layout.cshtml.puml
!include ./obj/Debug/net8.0/AeroAssist.MvcApplicationPartsAssemblyInfo.puml
!include ./obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./obj/Debug/net8.0/AeroAssist.RazorAssemblyInfo.puml
!include ./obj/Debug/net8.0/AeroAssist.GlobalUsings.g.puml
!include ./obj/Debug/net8.0/AeroAssist.AssemblyInfo.puml
@enduml
